"""
Fetch the fg-zettelkasten vault as a single in-memory bundle.

`summary_client` fetches one summary for the paper being processed. This module
fetches the *whole* vault instead, because the related-work brief has to rank
every paper the show has already covered against the new one, and 150+ Contents
API calls per run is not a reasonable way to do that.

The repo is public, so one unauthenticated tarball request (~12 MB) is both
fewer round-trips and better recall than a per-key fetch. It is parsed straight
from memory with `tarfile` — nothing is written to disk and `git` is never
shelled out to, so this behaves identically on a CI runner and a laptop.

Fetch once per run, not once per paper: generation is unthrottled, so a
five-paper run would otherwise download the same 12 MB five times.

Every failure path returns None. The caller then generates the episode with no
connections, exactly as it did before this module existed.
"""

import io
import json
import tarfile
from typing import Optional

import requests

# Members we care about inside the tarball, under the archive's top-level
# "<owner>-<repo>-<sha>/" directory.
_NOTE_PREFIX = "vault/Papers/"
_SUMMARY_PREFIX = "data/summaries/"

# Frontmatter keys lifted from a paper note. `topics` and `authors` are lists.
_SCALAR_KEYS = ("title", "year", "doi", "bibtex_key", "kind", "superseded_by")
_LIST_KEYS = ("authors", "topics")


def _parse_frontmatter(text: str) -> dict:
    """Extract the YAML frontmatter of a vault note without a YAML dependency.

    The notes are machine-generated by fg-zettelkasten's `note_builder`, so the
    frontmatter is a flat, predictable `key: value` block with quoted strings
    and single-line JSON-ish lists — a real YAML parser would buy nothing here.
    """
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    meta = {}
    for line in text[3:end].splitlines():
        if ":" not in line or line.startswith(" "):
            continue
        key, _, raw = line.partition(":")
        key, raw = key.strip(), raw.strip()
        if key in _LIST_KEYS:
            if raw.startswith("[") and raw.endswith("]"):
                items = [
                    item.strip().strip('"\'')
                    for item in raw[1:-1].split(",")
                ]
                meta[key] = [item for item in items if item]
        elif key in _SCALAR_KEYS:
            value = raw.strip('"\'')
            if value and value.lower() not in ("null", "none"):
                meta[key] = value
    return meta


def _body(text: str) -> str:
    """Return the note body with the frontmatter block removed."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:]
    return text


def fetch_vault_bundle(tarball_url: str, timeout: int = 120) -> Optional[dict]:
    """Return `{bibtex_key: {...}}` for every paper in the vault, or None.

    Each entry carries what the related-work ranker and brief need:
    `title`, `authors`, `year`, `doi`, `topics`, `abstract`, `key_claims`.
    Notes and summaries are joined on the bibtex key (the filename stem, which
    is also the `bibtex_key` frontmatter field).

    A note without a summary still gets an entry (title and topics are enough
    to rank it, if weakly); a summary without a note is skipped, since we would
    have no title to speak aloud.
    """
    try:
        resp = requests.get(tarball_url, timeout=timeout)
        resp.raise_for_status()
        archive = io.BytesIO(resp.content)
    except requests.RequestException as exc:
        print(f"  Note: fg-zettelkasten vault unavailable ({exc})")
        return None

    notes: dict = {}
    summaries: dict = {}
    try:
        with tarfile.open(fileobj=archive, mode="r:gz") as tar:
            for member in tar:
                if not member.isfile():
                    continue
                # Strip the "<owner>-<repo>-<sha>/" wrapper directory.
                path = member.name.split("/", 1)[-1]
                if path.startswith(_NOTE_PREFIX) and path.endswith(".md"):
                    key = path[len(_NOTE_PREFIX):-len(".md")]
                    handle = tar.extractfile(member)
                    if handle is None:
                        continue
                    notes[key] = handle.read().decode("utf-8", "replace")
                elif path.startswith(_SUMMARY_PREFIX) and path.endswith(".json"):
                    key = path[len(_SUMMARY_PREFIX):-len(".json")]
                    handle = tar.extractfile(member)
                    if handle is None:
                        continue
                    try:
                        summaries[key] = json.loads(
                            handle.read().decode("utf-8", "replace")
                        )
                    except ValueError:
                        continue
    except (tarfile.TarError, OSError, EOFError) as exc:
        print(f"  Note: could not read the fg-zettelkasten vault archive ({exc})")
        return None

    bundle = {}
    for key, text in notes.items():
        meta = _parse_frontmatter(text)
        # A superseded note is a content-free stub kept only so inbound
        # wikilinks resolve; citing one on air would point at nothing.
        if meta.get("superseded_by"):
            continue
        title = meta.get("title")
        if not title:
            continue
        summary = summaries.get(key) or {}
        bundle[key] = {
            "bibtex_key": meta.get("bibtex_key", key),
            "title": title,
            "authors": meta.get("authors", []),
            "year": meta.get("year"),
            "doi": meta.get("doi"),
            "topics": meta.get("topics", []),
            "abstract": summary.get("abstract", ""),
            "key_claims": _as_list(summary.get("key_claims")),
            "has_summary": bool(summary),
        }

    if not bundle:
        print("  Note: fg-zettelkasten vault archive contained no usable notes")
        return None
    print(f"  fg-zettelkasten vault: {len(bundle)} notes indexed")
    return bundle


def _as_list(value) -> list:
    """Normalise a summary field that fg-zettelkasten emits as str or list."""
    if not value:
        return []
    if isinstance(value, str):
        return [value]
    return [str(item) for item in value]


def spoken_reference(entry: dict) -> str:
    """Render a citation a TTS engine can read aloud.

    Never a bibtex key or a wikilink — those get pronounced letter by letter.
    """
    authors = entry.get("authors") or []
    year = entry.get("year")
    if not authors:
        return f"a {year} paper" if year else "an earlier paper"
    surname = authors[0].split()[-1] if authors[0].split() else authors[0]
    who = surname if len(authors) == 1 else f"{surname} and colleagues"
    return f"{who}, {year}" if year else who
